/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024.Admin;

import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author alexanderabboud
 */
public class AndraLand extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare; 
    /**
     * Creates new form AndraLand
     */
    public AndraLand(InfDB idb, String inloggadAnvandare) {
        this.idb=idb;
        this.inloggadAnvandare=inloggadAnvandare;
        initComponents();
        fyllCb();
        gomAlla();
    }
    
    public void fyllCb(){
        cbValjLand.removeAllItems();
        String sqlFraga="SELECT namn FROM land";
        
        ArrayList<String> namnLista=new ArrayList<>();
        
        try{
            namnLista=idb.fetchColumn(sqlFraga);
            
            for(String namn:namnLista){
                cbValjLand.addItem(namn);
            }
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void gomAlla(){
        
        //göm allt som har med valen att göra
        lblEkonomiBad.setVisible(false);
        lblNamnBad.setVisible(false);
        lblPolitikBad.setVisible(false);
        lblSprakBad.setVisible(false);
        lblTidzonBad.setVisible(false);
        lblValutaBad.setVisible(false);
        tfEkonomi.setVisible(false);
        tfNamn.setVisible(false);
        tfPolitik.setVisible(false);
        tfSprak.setVisible(false);
        tfTidzon.setVisible(false);
        tfValuta.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        btnAndra.setVisible(false);
       
        lblLid.setVisible(false);
        lblNamn.setVisible(false);
        lblBorttagen.setVisible(false);
        btnTaBort.setVisible(false);
        
        cbValjLand.setVisible(false);
    }
    
    
    
    public String selectLid(){
        String lid="111";
        try{
            String sqlFraga="SELECT lid FROM land where namn='" + cbValjLand.getSelectedItem() + "'";
            lid=idb.fetchSingle(sqlFraga);
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return lid;
        }
    
    public void taBortLand(int lid){
        
        String sqlFraga="DELETE FROM land WHERE lid=" + lid;
        try{
            idb.delete(sqlFraga);
            lblBorttagen.setVisible(true);
            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbhAndra = new javax.swing.JCheckBox();
        cbhTaBort = new javax.swing.JCheckBox();
        cbValjLand = new javax.swing.JComboBox<>();
        tfNamn = new javax.swing.JTextField();
        tfSprak = new javax.swing.JTextField();
        tfValuta = new javax.swing.JTextField();
        tfTidzon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfPolitik = new javax.swing.JTextField();
        tfEkonomi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNamnBad = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSprakBad = new javax.swing.JLabel();
        lblValutaBad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTidzonBad = new javax.swing.JLabel();
        lblPolitikBad = new javax.swing.JLabel();
        lblEkonomiBad = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();
        lblBorttagen = new javax.swing.JLabel();
        lblLid = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        btnAndra = new javax.swing.JButton();
        btnValj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbhAndra.setText("Ändra");
        cbhAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhAndraActionPerformed(evt);
            }
        });

        cbhTaBort.setText("Ta bort");
        cbhTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhTaBortActionPerformed(evt);
            }
        });

        cbValjLand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        tfNamn.setText("Namn");
        tfNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamnActionPerformed(evt);
            }
        });

        tfSprak.setText("Språk");

        tfValuta.setText("Valuta");

        tfTidzon.setText("Tidzon");

        jLabel1.setText("Namn");

        tfPolitik.setText("Politisk Struktur");

        tfEkonomi.setText("Ekonomi");

        jLabel2.setText("Språk");

        jLabel3.setText("Valuta");

        jLabel4.setText("Tidzon");

        lblNamnBad.setForeground(new java.awt.Color(255, 0, 51));
        lblNamnBad.setText("!");

        jLabel5.setText("Politisk Struktur");

        lblSprakBad.setForeground(new java.awt.Color(255, 0, 51));
        lblSprakBad.setText("!");

        lblValutaBad.setForeground(new java.awt.Color(255, 0, 51));
        lblValutaBad.setText("!");

        jLabel6.setText("Ekonomi");

        lblTidzonBad.setForeground(new java.awt.Color(255, 0, 51));
        lblTidzonBad.setText("!");

        lblPolitikBad.setForeground(new java.awt.Color(255, 0, 51));
        lblPolitikBad.setText("!");

        lblEkonomiBad.setForeground(new java.awt.Color(255, 0, 51));
        lblEkonomiBad.setText("!");

        lblNamn.setText("Namn");

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        lblBorttagen.setForeground(new java.awt.Color(0, 204, 0));
        lblBorttagen.setText("Användare borttagen");
        lblBorttagen.setBorder(new javax.swing.border.MatteBorder(null));
        lblBorttagen.setMaximumSize(new java.awt.Dimension(211, 17));
        lblBorttagen.setSize(new java.awt.Dimension(100, 17));

        lblLid.setText("lid");

        btnTillbaka.setText("X");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnAndra.setText("Ändra");

        btnValj.setText("Välj");
        btnValj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbhAndra)
                                .addGap(18, 18, 18)
                                .addComponent(cbhTaBort)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTillbaka))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfEkonomi)
                                            .addComponent(tfPolitik)
                                            .addComponent(tfTidzon)
                                            .addComponent(tfValuta)
                                            .addComponent(tfSprak, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSprakBad)
                                            .addComponent(lblValutaBad)
                                            .addComponent(lblTidzonBad)
                                            .addComponent(lblPolitikBad)
                                            .addComponent(lblEkonomiBad)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbValjLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnValj)
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTaBort)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblLid)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 26, Short.MAX_VALUE)))
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAndra)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBorttagen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNamnBad)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbhAndra)
                            .addComponent(cbhTaBort)
                            .addComponent(btnTillbaka)))
                    .addComponent(btnTaBort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLid)
                    .addComponent(lblNamn)
                    .addComponent(cbValjLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBorttagen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamnBad))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSprakBad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValutaBad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTidzon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTidzonBad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPolitik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolitikBad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEkonomiBad))
                .addGap(18, 18, 18)
                .addComponent(btnAndra)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamnActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
    String stringInt=lblLid.getText();
    int iInt=Integer.parseInt(stringInt);
    taBortLand(iInt);
    
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AdminMeny(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void cbhTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhTaBortActionPerformed
       if(cbhTaBort.isSelected()){
           cbhAndra.setSelected(false);
           gomAndra();
       }
    }//GEN-LAST:event_cbhTaBortActionPerformed
    public void gomAndra(){
        
        //göm allt om Ändra
        lblEkonomiBad.setVisible(false);
        lblNamnBad.setVisible(false);
        lblPolitikBad.setVisible(false);
        lblSprakBad.setVisible(false);
        lblTidzonBad.setVisible(false);
        lblValutaBad.setVisible(false);
        tfEkonomi.setVisible(false);
        tfNamn.setVisible(false);
        tfPolitik.setVisible(false);
        tfSprak.setVisible(false);
        tfTidzon.setVisible(false);
        tfValuta.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        btnAndra.setVisible(false);
        
        // så att man kan se de som tillhör ta bort
        lblLid.setVisible(true);
        lblNamn.setVisible(true);
        btnTaBort.setVisible(true);
        cbValjLand.setVisible(true);
    }
    
    public void gomTaBort() {
    // Visa allt om Ändra
    lblEkonomiBad.setVisible(true);
    lblNamnBad.setVisible(true);
    lblPolitikBad.setVisible(true);
    lblSprakBad.setVisible(true);
    lblTidzonBad.setVisible(true);
    lblValutaBad.setVisible(true);
    tfEkonomi.setVisible(true);
    tfNamn.setVisible(true);
    tfPolitik.setVisible(true);
    tfSprak.setVisible(true);
    tfTidzon.setVisible(true);
    tfValuta.setVisible(true);
    jLabel1.setVisible(true);
    jLabel2.setVisible(true);
    jLabel3.setVisible(true);
    jLabel4.setVisible(true);
    jLabel5.setVisible(true);
    jLabel6.setVisible(true);
    btnAndra.setVisible(true);
    cbValjLand.setVisible(true);

    // Göm det som tillhör ta bort
    lblLid.setVisible(false);
    lblNamn.setVisible(false);
    lblBorttagen.setVisible(false);
    btnTaBort.setVisible(false);
}
    
    
    
    private void cbhAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhAndraActionPerformed
        if(cbhAndra.isSelected()){
            cbhTaBort.setSelected(false);
            gomTaBort();
        }
    }//GEN-LAST:event_cbhAndraActionPerformed

    private void btnValjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjActionPerformed
      if(cbhTaBort.isSelected()){
          lblLid.setText(selectLid());
          int i=cbValjLand.getSelectedIndex();
          lblNamn.setText(cbValjLand.getItemAt(i));
      }
        
      
    }//GEN-LAST:event_btnValjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new AndraLand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnValj;
    private javax.swing.JComboBox<String> cbValjLand;
    private javax.swing.JCheckBox cbhAndra;
    private javax.swing.JCheckBox cbhTaBort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBorttagen;
    private javax.swing.JLabel lblEkonomiBad;
    private javax.swing.JLabel lblLid;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblNamnBad;
    private javax.swing.JLabel lblPolitikBad;
    private javax.swing.JLabel lblSprakBad;
    private javax.swing.JLabel lblTidzonBad;
    private javax.swing.JLabel lblValutaBad;
    private javax.swing.JTextField tfEkonomi;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfPolitik;
    private javax.swing.JTextField tfSprak;
    private javax.swing.JTextField tfTidzon;
    private javax.swing.JTextField tfValuta;
    // End of variables declaration//GEN-END:variables
}
