/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024.Admin;

import ngo2024.Validering;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;

/**
 *
 * @author alexanderabboud
 */
public class LaggTillPartner extends javax.swing.JFrame {

    private InfDB idb;
    private String epost;  
    boolean kontrollOk;
    
   /**
     * Initierar LaggTillPartner objekt 
     * låter administratören lägga till en ny partner
     *
     * @param idb initierar fält för att interagera med databasen
     * @param epost eposten till den inloggade användaren
     */

    public LaggTillPartner(InfDB idb, String epost) {
        this.idb=idb;
        this.epost=epost;
        initComponents();
        kontrollOk=false;
        lblError.setVisible(false);
        lblSkapad.setVisible(false);
        lblNamn.setVisible(true);
        lblKP.setVisible(true);
        lblEpost.setVisible(true);
        lblTelefon.setVisible(true);
        lblAdress.setVisible(true);
        lblBransch.setVisible(true);
        fyllCb();
        gomBad();

    }
    
    /**
     * fyller i combo box med namn på städer
     */
    
    public void fyllCb(){
        
        cbStad.removeAllItems();
        String sqlFraga="SELECT namn FROM stad";
        
        ArrayList<String> namnLista=new ArrayList<>();
        
        try{
            namnLista=idb.fetchColumn(sqlFraga);
            
            for(String namn:namnLista){
                cbStad.addItem(namn);
            }
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void gomBad(){
        lblNamnBad.setVisible(false);
        lblKPersonBad.setVisible(false);
        lblEpostBad.setVisible(false);
        lblTelefonBad.setVisible(false);
        lblAdressBad.setVisible(false);
        lblBranschBad.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblError = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        tfAdress = new javax.swing.JTextField();
        lblBransch = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblKP = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSkapad = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        lblEpost = new javax.swing.JLabel();
        tfBransch = new javax.swing.JTextField();
        btnSkapa = new javax.swing.JButton();
        tfNamn = new javax.swing.JTextField();
        tfKPerson = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        lblNamnBad = new javax.swing.JLabel();
        lblKPersonBad = new javax.swing.JLabel();
        lblEpostBad = new javax.swing.JLabel();
        lblTelefonBad = new javax.swing.JLabel();
        lblAdressBad = new javax.swing.JLabel();
        lblBranschBad = new javax.swing.JLabel();
        cbStad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setText("Error!");

        lblAdress.setText("Adress");

        tfAdress.setText("123 exempel, bobla");

        lblBransch.setText("Bransch");

        lblTelefon.setText("Telefon");

        lblNamn.setText("Namn");

        lblKP.setText("Kontaktperson");

        jLabel7.setText("Lägg till partner");

        lblSkapad.setForeground(new java.awt.Color(0, 204, 51));
        lblSkapad.setText("Skapad");

        btnTillbaka.setText("X");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblEpost.setText("Kontakt epost");

        tfBransch.setText("Bransch");

        btnSkapa.setText("Skapa");
        btnSkapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaActionPerformed(evt);
            }
        });

        tfNamn.setText("Namn");
        tfNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamnActionPerformed(evt);
            }
        });

        tfKPerson.setText("KontaktPerson");

        tfEpost.setText("example@mail.com");

        tfTelefon.setText("123-123-1234");

        lblNamnBad.setForeground(new java.awt.Color(255, 0, 51));
        lblNamnBad.setText("!");

        lblKPersonBad.setForeground(new java.awt.Color(255, 0, 51));
        lblKPersonBad.setText("!");

        lblEpostBad.setForeground(new java.awt.Color(255, 0, 51));
        lblEpostBad.setText("!");

        lblTelefonBad.setForeground(new java.awt.Color(255, 0, 51));
        lblTelefonBad.setText("!");

        lblAdressBad.setForeground(new java.awt.Color(255, 0, 51));
        lblAdressBad.setText("!");

        lblBranschBad.setForeground(new java.awt.Color(255, 0, 51));
        lblBranschBad.setText("!");

        cbStad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 417, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnSkapa))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKP)
                            .addComponent(lblTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBransch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSkapad)
                        .addGap(54, 54, 54)
                        .addComponent(lblError))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfBransch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfAdress)
                                .addComponent(tfTelefon)
                                .addComponent(tfEpost)
                                .addComponent(tfKPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNamnBad, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblKPersonBad, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEpostBad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTelefonBad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAdressBad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBranschBad, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnTillbaka))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamnBad)
                    .addComponent(lblNamn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKPersonBad)
                            .addComponent(lblKP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEpostBad)
                            .addComponent(lblEpost))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefonBad)
                            .addComponent(lblTelefon))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdressBad)
                            .addComponent(lblAdress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBransch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBranschBad)
                            .addComponent(lblBransch))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSkapa)
                            .addComponent(lblSkapad)
                            .addComponent(lblError))
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * kontrollerar så att allt är valid
     */
    
    public void totalKontroll() {
    Boolean totOk = true;

    if (!kPersonKontroll()) {
        totOk = false;
        lblKPersonBad.setVisible(true);

    } else if (!namnKontroll()) {
        totOk = false;
        lblNamnBad.setVisible(true);

    } else if (!epostKontroll()) {
        totOk = false;
        lblEpostBad.setVisible(true);
    } else if (!telefonKontroll()) {
        totOk = false;
        lblTelefonBad.setVisible(true);
    } else if (!adressKontroll()) {
        totOk = false;
        lblAdressBad.setVisible(true);
    } else if (!branschKontroll()) {
        totOk = false;
        lblBranschBad.setVisible(true);
    }

    kontrollOk = totOk;
}
    
    /**
     * hämtar ut högsta partner ID
     */

    
public int hogstaPid(){
        int hogsta=0;
        String sqlFraga="Select MAX(pid) FROM partner";
        try{
            String max=idb.fetchSingle(sqlFraga);
            hogsta=Integer.parseInt(max);
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        System.out.println(hogsta);
        return hogsta+1;
    }

    /**
     * kontrollerar kontaktperson
     */
    
    public boolean kPersonKontroll(){
        Validering valid = new Validering(idb);
        String namn = tfKPerson.getText();
        // kontrollerar kPerson vilekt är ett namn
    if (valid.checkNamn(namn) && valid.checkStorlek(255, namn)) {
            lblKPersonBad.setVisible(false);
            return true;
    } else {
            lblKPersonBad.setVisible(true);
            return false;
    }
    }
    
    /**
     * kontrollerar namn för att se till att det är valid
     */
    
    public boolean namnKontroll(){
        Validering valid = new Validering(idb);
        String namn = tfNamn.getText();
        // kontrollerar namn format
    if (valid.checkNamn(namn) && valid.checkStorlek(255, namn)) {
            lblNamnBad.setVisible(false);
            return true;
    } else {
            lblNamnBad.setVisible(true);
            return false;
    }
    }

    /**
     * kontrollerar så att eposten är valid
     */
    
    public boolean epostKontroll(){
        Validering valid = new Validering(idb);
        String epost = tfEpost.getText();
    if (valid.checkEpost(epost)&& valid.checkStorlek(255, epost)) {
            lblEpostBad.setVisible(false);
            return true;
    } else {
            lblEpostBad.setVisible(true);
            return false;
    }
    }
    
    /**
     * kontrollerar så att telefon nummer är valid
     */
    
    public boolean telefonKontroll(){
        Validering valid = new Validering(idb);
        String telefon = tfTelefon.getText();
    if (valid.checkTelefon(telefon)&& valid.checkStorlek(20, telefon)) {
            lblTelefonBad.setVisible(false);
            return true;
    } else {
            lblTelefonBad.setVisible(true);
            return false;
    }
    }
    
    

    /**
     * kontrollerar så att adress är valid
     */

    
    public boolean adressKontroll(){
        Validering valid = new Validering(idb);
        String adress = tfAdress.getText();
    if (valid.checkAdress(adress)&& valid.checkStorlek(255, adress)) {
            lblAdressBad.setVisible(false);
            return true;
    } else {
            lblAdressBad.setVisible(true);
            return false;
    }
    }
    
    /**
     * kontrollerar så att bransch är valid
     */
    
    public boolean branschKontroll(){
        Validering valid = new Validering(idb);
        String bransch = tfBransch.getText();
    if (valid.checkFornamn(bransch)&& valid.checkStorlek(255, bransch)) {
            lblBranschBad.setVisible(false);
            return true;
    } else {
            lblBranschBad.setVisible(true);
            return false;
    }
    }
    
    /**
     * hämtar ut stads id
     */
    
    public int getStad(){
        int i=cbStad.getSelectedIndex();
        int sid=0;
        String sql="SELECT sid FROM stad WHERE namn='" + cbStad.getItemAt(i) + "'";
        System.out.println(sql);
        try{
            String sSid=idb.fetchSingle(sql);
            sid=Integer.parseInt(sSid);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        return sid;
    }
    
    
    
    
    
    
    private void btnSkapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaActionPerformed
        totalKontroll();
        int hogsta=hogstaPid();
        String sqlFraga="INSERT INTO partner VALUES(" + hogsta + ",'" + tfNamn.getText() + "','"
        + tfKPerson.getText() + "','" + tfEpost.getText() + "', '" + tfTelefon.getText() + "','"
        + tfAdress.getText() + "','" + tfBransch.getText() + "', " + getStad() + ")";
        System.out.println(sqlFraga);
        if(kontrollOk==true){
            try{

                idb.insert(sqlFraga);
                System.out.println(sqlFraga);

            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
            lblError.setVisible(false);
            lblSkapad.setVisible(true);
        }
        else{
            lblError.setVisible(true);
        }
    }//GEN-LAST:event_btnSkapaActionPerformed

    private void tfNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamnActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LaggTillPartner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkapa;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbStad;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAdressBad;
    private javax.swing.JLabel lblBransch;
    private javax.swing.JLabel lblBranschBad;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblEpostBad;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblKP;
    private javax.swing.JLabel lblKPersonBad;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblNamnBad;
    private javax.swing.JLabel lblSkapad;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTelefonBad;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfBransch;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfKPerson;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
