/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024.Admin;
import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import java.util.Random;
import ngo2024.Validering;
import oru.inf.InfException;

/**
 *
 * @author alexanderabboud
 */
public class LaggTillAnstalld extends javax.swing.JFrame {
private InfDB idb;
private boolean created;
private Random randomizer;
boolean kontrollOk;
private String epost;
private HashMap<String, String> mentorLista;

    /**
     * Creates new form LaggTillAnstalld1
     */
    public LaggTillAnstalld(InfDB idb,String epost) {
        this.idb=idb;
        mentorLista = new HashMap<>();
        initComponents();
        created=false;
        kontrollOk=false;
        gomBad();
        gomFalt();
        lblLyckades.setVisible(false);
        lblError.setVisible(false);
        randomizer=new Random();
        this.epost=epost;
    }
    
    private void gomBad(){
        lblDatumBad1.setVisible(false);
        lblEpostBad.setVisible(false);
        lblTelefonBad.setVisible(false);
        lblAdressBad.setVisible(false);
        lblEfternamnBad.setVisible(false);
        lblFornamnBad.setVisible(false);
        lblAnsvarBad.setVisible(false);
        lblLosenBad.setVisible(false);
    }
    
    //gömmer fältet mentor, comboboxen och meddelande som kommer upp efter hand
    private void gomFaltAdmin(){
        lblMentor.setVisible(false);
        cbMentor.setVisible(false);    
        cbIngenMentor.setVisible(false);
        lblAid.setVisible(false);
        tfAnsvarighetsOmrade.setVisible(false);
        lblBehorighet.setVisible(true);
        cbBehorighet.setVisible(true);
    }
    
    private void gomFalt(){
        lblMentor.setVisible(false);
        cbMentor.setVisible(false);    
        cbIngenMentor.setVisible(false);
        lblAid.setVisible(false);
        tfAnsvarighetsOmrade.setVisible(false);
        lblBehorighet.setVisible(false);
        cbBehorighet.setVisible(false);
    }
    
    private void gomFaltHandlaggare(){
        lblMentor.setVisible(true);
        cbMentor.setVisible(true);    
        cbIngenMentor.setVisible(true);
        lblAid.setVisible(true);
        tfAnsvarighetsOmrade.setVisible(true);
        lblBehorighet.setVisible(false);
        cbBehorighet.setVisible(false);
    }
    
//

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEfternamn = new javax.swing.JLabel();
        lblEfternamnBad = new javax.swing.JLabel();
        lblFornamn = new javax.swing.JLabel();
        lblAdressBad = new javax.swing.JLabel();
        btnSkapa = new javax.swing.JButton();
        lblTelefonBad = new javax.swing.JLabel();
        lblDatumBad1 = new javax.swing.JLabel();
        btnRandom = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblLyckades = new javax.swing.JLabel();
        cbAvdelning = new javax.swing.JComboBox<>();
        lblEpostBad = new javax.swing.JLabel();
        tfLosenord = new javax.swing.JTextField();
        tfFornamn = new javax.swing.JTextField();
        tfEfternamn = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        lblAid = new javax.swing.JLabel();
        tfEpost = new javax.swing.JTextField();
        lblAnsvarBad = new javax.swing.JLabel();
        tfTelefon = new javax.swing.JTextField();
        cbIngenMentor = new javax.swing.JCheckBox();
        lblMentor = new javax.swing.JLabel();
        cbMentor = new javax.swing.JComboBox<>();
        tfAnstallDatum = new javax.swing.JTextField();
        lblAvdelning = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        tfAnsvarighetsOmrade = new javax.swing.JTextField();
        lblAnstallDatum = new javax.swing.JLabel();
        chbHandlaggare = new javax.swing.JCheckBox();
        lblTelefon = new javax.swing.JLabel();
        chbAdmin = new javax.swing.JCheckBox();
        lblEpost = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        lblAdress = new javax.swing.JLabel();
        lblFornamnBad = new javax.swing.JLabel();
        lblBehorighet = new javax.swing.JLabel();
        cbBehorighet = new javax.swing.JComboBox<>();
        lblLosenBad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEfternamn.setText("Efternamn");

        lblEfternamnBad.setForeground(new java.awt.Color(255, 0, 51));
        lblEfternamnBad.setText("!");

        lblFornamn.setText("Förnamn");

        lblAdressBad.setForeground(new java.awt.Color(255, 0, 51));
        lblAdressBad.setText("!");

        btnSkapa.setText("Skapa");
        btnSkapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaActionPerformed(evt);
            }
        });

        lblTelefonBad.setForeground(new java.awt.Color(255, 0, 51));
        lblTelefonBad.setText("!");

        lblDatumBad1.setForeground(new java.awt.Color(255, 0, 51));
        lblDatumBad1.setText("!");

        btnRandom.setText("Random");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setText("Error!");

        lblLyckades.setForeground(new java.awt.Color(51, 204, 0));
        lblLyckades.setText("Lyckades!");

        cbAvdelning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Klimat", "Samhälle", "Teknik" }));

        lblEpostBad.setForeground(new java.awt.Color(255, 0, 51));
        lblEpostBad.setText("!");

        tfLosenord.setText("Lösenord");
        tfLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLosenordActionPerformed(evt);
            }
        });

        tfFornamn.setText("Förnamn");

        tfEfternamn.setText("Efternamn");

        tfAdress.setText("123 blabla, bobla");

        lblAid.setText("aid");

        tfEpost.setText("example@mail.com");
        tfEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEpostActionPerformed(evt);
            }
        });

        lblAnsvarBad.setForeground(new java.awt.Color(255, 0, 0));
        lblAnsvarBad.setText("!");

        tfTelefon.setText("123-123-1234");
        tfTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonActionPerformed(evt);
            }
        });

        cbIngenMentor.setText("Ingen mentor");
        cbIngenMentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIngenMentorActionPerformed(evt);
            }
        });

        lblMentor.setText("Mentor");

        cbMentor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMentorActionPerformed(evt);
            }
        });

        tfAnstallDatum.setText("yyyy-mm-dd");
        tfAnstallDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnstallDatumActionPerformed(evt);
            }
        });

        lblAvdelning.setText("Avdelning");

        lblLosenord.setText("Lösenord");

        tfAnsvarighetsOmrade.setText("AnsvarighetsOmråde");

        lblAnstallDatum.setText("Anställningsdatum");

        chbHandlaggare.setText("Handläggare");
        chbHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbHandlaggareActionPerformed(evt);
            }
        });

        lblTelefon.setText("Telefon");

        chbAdmin.setText("Admin");
        chbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAdminActionPerformed(evt);
            }
        });

        lblEpost.setText("Epost");

        btnTillbaka.setText("X");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblAdress.setText("Adress");

        lblFornamnBad.setForeground(new java.awt.Color(255, 0, 51));
        lblFornamnBad.setText("!");

        lblBehorighet.setText("Behörighetsnivå");

        cbBehorighet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        lblLosenBad.setForeground(new java.awt.Color(255, 0, 51));
        lblLosenBad.setText("!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBehorighet)
                        .addGap(18, 18, 18)
                        .addComponent(cbBehorighet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSkapa)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMentor)
                                .addGap(18, 18, 18)
                                .addComponent(cbMentor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfAnsvarighetsOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAnsvarBad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAid)
                        .addGap(18, 18, 18)
                        .addComponent(cbIngenMentor)
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblLyckades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTillbaka))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chbAdmin)
                                        .addGap(18, 18, 18)
                                        .addComponent(chbHandlaggare))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAnstallDatum)
                                            .addComponent(lblTelefon)
                                            .addComponent(lblEpost)
                                            .addComponent(lblAdress)
                                            .addComponent(lblEfternamn)
                                            .addComponent(lblFornamn)
                                            .addComponent(lblLosenord)
                                            .addComponent(lblAvdelning))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tfAnstallDatum)
                                                    .addComponent(tfLosenord)
                                                    .addComponent(tfTelefon)
                                                    .addComponent(tfEpost)
                                                    .addComponent(tfAdress)
                                                    .addComponent(tfEfternamn)
                                                    .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblEfternamnBad)
                                                    .addComponent(lblFornamnBad)
                                                    .addComponent(lblDatumBad1)
                                                    .addComponent(lblAdressBad)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblLosenBad)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(lblEpostBad)
                                                    .addComponent(lblTelefonBad)))
                                            .addComponent(cbAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblError))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTillbaka)
                            .addComponent(lblLyckades)
                            .addComponent(lblError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFornamn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFornamnBad)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEfternamn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEfternamnBad)
                                        .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdress)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAdressBad)))
                                .addGap(12, 12, 12)
                                .addComponent(lblEpost))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEpostBad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTelefon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAnstallDatum))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefonBad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAnstallDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatumBad1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLosenord, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRandom)
                        .addComponent(lblLosenBad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(cbAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbAdmin)
                    .addComponent(chbHandlaggare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMentor)
                    .addComponent(cbMentor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAid)
                    .addComponent(cbIngenMentor))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAnsvarighetsOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnsvarBad))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSkapa)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBehorighet)
                            .addComponent(cbBehorighet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaActionPerformed
        totalKontroll(idb);
        boolean admin=isAdmin();
        int hogsta=hogstaAid(idb);

        if(kontrollOk==true && alltMed()==true){
            try{
                String sqlFraga="INSERT INTO anstalld VALUES(" + hogsta + ", '" + tfFornamn.getText() +"', '"
                + tfEfternamn.getText() + "', '" + tfAdress.getText() + "', '"+tfEpost.getText() + "', '" + tfTelefon.getText() + "', '"
                + tfAnstallDatum.getText() + "', '" + tfLosenord.getText() + "', " + getAvdelning() + ")";

                if(admin==true){
                    String sqlAdmin="INSERT INTO admin VALUES(" + hogsta + ", " + getSelectedBehorighet() + ")";
                    idb.insert(sqlFraga);
                    idb.insert(sqlAdmin);
                    System.out.println(sqlAdmin);

                }
                else if(admin==false){
                    if(!cbIngenMentor.isSelected()){
                       String sqlHandlaggare="INSERT INTO handlaggare VALUES(" + hogsta + ", '" + tfAnsvarighetsOmrade.getText() + "', " + getSelectedAid() + ")";
                        idb.insert(sqlFraga);
                        idb.insert(sqlHandlaggare);
                        System.out.println(sqlHandlaggare);}
                    else {
                        String sqlHandlaggare="INSERT INTO handlaggare VALUES(" + hogsta + ", '" + tfAnsvarighetsOmrade.getText() + "', null)";
                        idb.insert(sqlFraga);
                        idb.insert(sqlHandlaggare);
                        System.out.println(sqlHandlaggare);}
                }
            }

            catch(InfException ex){
                System.out.println(ex.getMessage());
            }
            lblLyckades.setVisible(true);
            lblError.setVisible(false);
        }

        else if (kontrollOk==false){
            lblError.setVisible(true);

        }
    }//GEN-LAST:event_btnSkapaActionPerformed

    public void totalKontroll(InfDB idb){
        Boolean totOk=true;
        if(epostKontroll(idb)==false){
            totOk=false;
        }
        else if(!datumKontroll(idb)){
            totOk=false;
        }
        else if(!fornamnKontroll(idb)) {
        totOk = false;
        }
        else if(!efternamnKontroll(idb)) {
        totOk = false;
        }
        else if(!adressKontroll(idb)) {
        totOk = false;
        }
        else if(!telefonKontroll(idb)) {
        totOk = false;
        }
        else if(!AnsvarKontroll(idb)){
            totOk=false;
        }
        else if(!losenKontroll()){
            totOk=false;
        }
        
        kontrollOk=totOk;
    }

    
    public boolean datumKontroll(InfDB idb){
        Validering valid = new Validering(idb); 
    
    // Hämta text från textfältet
    String datum = tfAnstallDatum.getText(); 
    
    // Kontrollera om e-postadressen är giltig
    if (valid.checkDatum(datum)) {
        lblDatumBad1.setVisible(false); // Göm varning
        return true;
    } else {
        lblDatumBad1.setVisible(true); // Visa varning
        return false;
    }
    }
    
    /**
     * Anropar kontroll av att nytt förnamn innehåller accepterade tecken 
     * Ger false om valideringen visar att fel uppstått
     * 
     * @param idb databasen som kallas för validering
     */
    public boolean fornamnKontroll(InfDB idb) {
        Validering valid = new Validering(idb);
        String fornamn = tfFornamn.getText();
    if (valid.checkFornamn(fornamn)&& valid.checkStorlek(100, fornamn)) {
        lblFornamnBad.setVisible(false); // Göm varning
        return true;
    } else {
        lblFornamnBad.setVisible(true); // Visa varning
        return false;
    }
    }
    
    /**
     * Anropar kontroll av att nytt efternamn innehåller accepterade tecken 
     * Ger false om valideringen visar att fel uppstått
     * 
     * @param idb databasen som används för validering
     */
    public boolean efternamnKontroll(InfDB idb) {
        Validering valid = new Validering(idb);
        String efternamn = tfEfternamn.getText();
    if (valid.checkEfternamn(efternamn) && valid.checkStorlek(100, efternamn)) {
            lblEfternamnBad.setVisible(false);
            return true;
    } else {
            lblEfternamnBad.setVisible(true);
            return false;
        }
    }
    
    /**
     * Anropar kontroll av att ny adress är korrekt formaterad
     * samt innehåller accepterade tecken 
     * Ger false om valideringen visar att fel uppstått
     * 
     * @param idb databasen som används för validering
     */
    public boolean adressKontroll(InfDB idb) {
        Validering valid = new Validering(idb);
        String adress = tfAdress.getText();
        if (valid.checkAdress(adress)&& valid.checkStorlek(255, adress)) {
            lblAdressBad.setVisible(false);
            return true;
        } else {
            lblAdressBad.setVisible(true);
            return false;
        }}
    
    /**
     * Anropar kontroll av att nytt telefonnummer är korrekt formaterad,
     * samt innehåller accepterade tecken 
     * Ger false om valideringen visar att fel uppstått
     * 
     * @param idb databasen som används för validering
     */
    public boolean telefonKontroll(InfDB idb) {
        Validering valid = new Validering(idb);
        String telefon = tfTelefon.getText();
    if (valid.checkTelefon(telefon)&& valid.checkStorlek(20, telefon)) {
            lblTelefonBad.setVisible(false);
            return true;
    } else {
            lblTelefonBad.setVisible(true);
            return false;
    }
    }
    
    /**
     * Anropar kontroll av att ny epost är korrekt formaterad,
     * samt innehåller accepterade tecken 
     * Ger false om valideringen visar att fel uppstått
     * 
     * @param idb databasen som används för validering
     */
    public boolean epostKontroll(InfDB idb){
    Validering valid = new Validering(idb); 
    
    // Hämta text från textfältet
    String tfepost = tfEpost.getText(); 
    
    // Kontrollera om e-postadressen är giltig
    if (valid.checkEpost(tfepost)&& valid.checkStorlek(255, tfepost)) {
        lblEpostBad.setVisible(false); // Göm varning
        return true;
    } else {
        lblEpostBad.setVisible(true); // Visa varning
        return false;
        
    }}
public boolean losenKontroll() {
        Validering valid = new Validering(idb);

        // Hämta text från textfältet
        String losen = tfLosenord.getText();

        // Kontrollera om e-postadressen är giltig
        if (valid.checkLosenord(losen) && valid.checkStorlek(255, losen)) {
          lblLosenBad.setVisible(false);
            return true;
        } else {
            lblLosenBad.setVisible(true);
            return false;
        }
    }
    
    /**
     * Kontrollerar att Ansvarighets Område label fylls med accepterade tecken 
     * samt inte överskrider visst antal tecken
     * 
     * @param idb databasen som kallas för validering
     */
    public boolean AnsvarKontroll(InfDB idb){
            Validering valid = new Validering(idb); 
          // Hämta text från textfältet
    String ansvar = tfAnsvarighetsOmrade.getText(); 
    
    // Kontrollera om ANsvarighetsområdet är ok är giltig
    if(valid.checkAnsvar(ansvar)&& valid.checkStorlek(255, ansvar)) {
        return true;
    } else {
        return false;
        
    }}  
    
    /**
     * Skapar nytt aid till ny användare. 
     * Tilldelar nummer som är +1 efter högsta nuvarande aid
     * 
     * @param idb databasen som kallas för validering
     */
    public int hogstaAid(InfDB idb){
        int hogsta=0;
        String sqlFraga="Select MAX(aid) FROM anstalld";
        try{
            String max=idb.fetchSingle(sqlFraga);
            hogsta=Integer.parseInt(max);
        }
        catch(InfException ex){
            System.out.println(ex.getMessage());
        }
        System.out.println(hogsta);
        return hogsta+1;
    }
    
    /**
     * Hämtar vilken avdelning användaren ska tilldelas
     * hämtas från combo box vald avdelning
     */
private int getAvdelning(){
    int avdelning=0;
    String val=cbAvdelning.getSelectedItem().toString();
    switch (val) {
        case "Klimat":
            avdelning=1;
            break;
        case "Teknik":
            avdelning=3;
            break;
        case "Samhälle":
            avdelning=2;
            break;
        default:
            break;
    }
   return avdelning;
}

/**
     * Genererar slumpat lösenord 
     */

    private String randomPassword(){
        String losen="";
        for(int i=0; i<11; i++){
            int ny=randomizer.nextInt(9);
            String nya=Integer.toString(ny);
            losen+=nya;
        }
        return losen;
    }
    
    

private void fyllCbMentor(){
    String sqlFraga = "SELECT CONCAT(fornamn, ' ', efternamn) as namn FROM anstalld WHERE aid IN "
            + "(SELECT aid FROM handlaggare)";
    
    try {
    ArrayList<String> handlaggarLista = idb.fetchColumn(sqlFraga);
    
    for(String namn: handlaggarLista){
        String sqlAid = "SELECT aid FROM anstalld where CONCAT(fornamn, ' ', efternamn) = '"
                    + namn + "'";
        String aid = idb.fetchSingle(sqlAid);
        cbMentor.addItem(namn);
        mentorLista.put(aid, namn);
    }
   
    lblAid.setText(getSelectedAid());
    
    } catch (InfException ex){
        System.out.println(ex.getMessage());
    }
    
}


private String getSelectedAid(){
        String selectedMentor = (String) cbMentor.getSelectedItem();
        String aid = " ";
        
        for(String id : mentorLista.keySet()){
            String namn = mentorLista.get(id);
            if(selectedMentor != null && selectedMentor.equals(namn)){
                aid = id;               
            }
        }
        return aid;
}

private String getSelectedBehorighet(){
    String selectedB = (String) cbBehorighet.getSelectedItem();

    return selectedB;
}
    
private boolean isAdmin(){

    boolean svar=false;
    if(chbHandlaggare.isSelected()){
        svar=false;
    }
    else if(chbAdmin.isSelected()){
        svar=true;
    }
    else{
        lblAnsvarBad.setVisible(true);
    }
    return svar;
}
  
public boolean alltMed(){
    boolean alltMed=false;
    // kontrollerar behörigheter är valda
    if(chbHandlaggare.isSelected()==false && chbAdmin.isSelected()==false){
    alltMed=false;
}
    else{
        alltMed=true;
    }
    return alltMed;
}    

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        tfLosenord.setText(randomPassword());
    }//GEN-LAST:event_btnRandomActionPerformed

    private void tfLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLosenordActionPerformed

    private void tfEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEpostActionPerformed

    }//GEN-LAST:event_tfEpostActionPerformed

    private void tfTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonActionPerformed

    private void cbIngenMentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIngenMentorActionPerformed
        if(cbIngenMentor.isSelected()){
            cbMentor.setVisible(false);
            lblAid.setVisible(false);
        } else if (!cbIngenMentor.isSelected()){
            cbMentor.setVisible(true);
            lblAid.setVisible(true);
        }
    }//GEN-LAST:event_cbIngenMentorActionPerformed

    private void cbMentorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMentorActionPerformed
        lblAid.setText(getSelectedAid());
    }//GEN-LAST:event_cbMentorActionPerformed

    private void tfAnstallDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnstallDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnstallDatumActionPerformed

    private void chbHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbHandlaggareActionPerformed
        if(chbHandlaggare.isSelected()){
            chbAdmin.setSelected(false);
            gomFaltHandlaggare();
            fyllCbMentor();
        }
    }//GEN-LAST:event_chbHandlaggareActionPerformed

    private void chbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAdminActionPerformed
        if(chbAdmin.isSelected()){
            chbHandlaggare.setSelected(false);
            gomFaltAdmin();
        }
    }//GEN-LAST:event_chbAdminActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LaggTillAnstalld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnSkapa;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbAvdelning;
    private javax.swing.JComboBox<String> cbBehorighet;
    private javax.swing.JCheckBox cbIngenMentor;
    private javax.swing.JComboBox<String> cbMentor;
    private javax.swing.JCheckBox chbAdmin;
    private javax.swing.JCheckBox chbHandlaggare;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAdressBad;
    private javax.swing.JLabel lblAid;
    private javax.swing.JLabel lblAnstallDatum;
    private javax.swing.JLabel lblAnsvarBad;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblBehorighet;
    private javax.swing.JLabel lblDatumBad1;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEfternamnBad;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblEpostBad;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblFornamnBad;
    private javax.swing.JLabel lblLosenBad;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblLyckades;
    private javax.swing.JLabel lblMentor;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTelefonBad;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAnstallDatum;
    private javax.swing.JTextField tfAnsvarighetsOmrade;
    private javax.swing.JTextField tfEfternamn;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfFornamn;
    private javax.swing.JTextField tfLosenord;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
