/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import TabellDesign.MultiLineCellRenderer;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author linneagottling
 */
public class GlobalaMal extends javax.swing.JFrame {

    private InfDB idb;
    private DefaultTableModel model;

    /**
     * Initierar GlobalaMal objekt 
     * Ger sida med tabell med alla globala mål samt deras beskrivning
     *
     * @param idb initierar fält för att interagera med databasen
     */
    public GlobalaMal(InfDB idb) {
        this.idb = idb;
        initComponents();
        konstrueraTabell();
        malTabell();
    }

    /**
     * Skapar tabellmodel för att hantera data om avdelningens anställda
     */
    private void konstrueraTabell() {
        model = (DefaultTableModel) tblGlobalaMal.getModel();
        model.setRowCount(0);
        tabellDesign();
    }

    /**
     * Bestämmer hur tabellen med anställdas information ska formateras
     */
    private void tabellDesign() {
        //fixar tabellens bredd
        tblGlobalaMal.getColumnModel().getColumn(0).setPreferredWidth(138);  // För kort text
        tblGlobalaMal.getColumnModel().getColumn(1).setPreferredWidth(138); 
        tblGlobalaMal.getColumnModel().getColumn(2).setPreferredWidth(300); // För längre text
        tblGlobalaMal.getColumnModel().getColumn(3).setPreferredWidth(138);

        tblGlobalaMal.getColumnModel().getColumn(0).setCellRenderer(new MultiLineCellRenderer());
        tblGlobalaMal.getColumnModel().getColumn(1).setCellRenderer(new MultiLineCellRenderer());
        tblGlobalaMal.getColumnModel().getColumn(2).setCellRenderer(new MultiLineCellRenderer());
        tblGlobalaMal.getColumnModel().getColumn(3).setCellRenderer(new MultiLineCellRenderer());

        for (int row = 0; row < tblGlobalaMal.getRowCount(); row++) {
            int rowHeight = tblGlobalaMal.getRowHeight();
            for (int column = 0; column < tblGlobalaMal.getColumnCount(); column++) {
                Component comp = tblGlobalaMal.prepareRenderer(tblGlobalaMal.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }
            tblGlobalaMal.setRowHeight(row, rowHeight);
        }
    }

    /**
     * Används för att lägga till rad i tabell
     */
    private void laggTillNyRad(String mal, String malnummer,
            String beskrivning, String prioritet) {
        model.addRow(new Object[]{mal, malnummer, beskrivning, prioritet});
    }

    /**
     * sparar information om globalt mål. Lägger till i tabellen
     */
    private void malTabell() {

        try {
            String sqlFraga = "SELECT namn, malnummer, beskrivning, prioritet "
                    + "FROM hallbarhetsmal";

            ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sqlFraga);

            for (HashMap<String, String> rad : resultat) {
                String mal = rad.get("namn");
                String malnummer = rad.get("malnummer");
                String beskrivning = rad.get("beskrivning");
                String prioritet = rad.get("prioritet");

                //lägger till rad i tabellen
                laggTillNyRad(mal, malnummer, beskrivning, prioritet);

            }
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGlobalaMal = new javax.swing.JLabel();
        btClose = new javax.swing.JButton();
        spPanel = new javax.swing.JScrollPane();
        tblGlobalaMal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGlobalaMal.setText("Globala målen:");

        btClose.setText("X");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        tblGlobalaMal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mål", "Målnummer", "Beskrivning", "Prioritet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGlobalaMal.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        spPanel.setViewportView(tblGlobalaMal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGlobalaMal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btClose)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGlobalaMal)
                    .addComponent(btClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlobalaMal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlobalaMal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlobalaMal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlobalaMal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GlobalaMal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JLabel lblGlobalaMal;
    private javax.swing.JScrollPane spPanel;
    private javax.swing.JTable tblGlobalaMal;
    // End of variables declaration//GEN-END:variables
}
