/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.Random;

/**
 *
 * @author alexanderabboud
 */
public class LaggTillAnstalld extends javax.swing.JFrame {
private InfDB idb;
private boolean created;
private Random randomizer;
boolean kontrollOk;

    /**
     * Creates new form LaggTillAnstalld
     */
    public LaggTillAnstalld(InfDB idb) {
        this.idb=idb;
        initComponents();
        created=false;
        kontrollOk=false;
        lblLyckades.setVisible(false);
        lblError.setVisible(false);
        lblDatumBad1.setVisible(false);
        lblEpostBad.setVisible(false);
        lblTelefonBad.setVisible(false);
        lblAdressBad.setVisible(false);
        lblEfternamnBad.setVisible(false);
        lblFornamnBad.setVisible(false);
        randomizer=new Random();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSkapa = new javax.swing.JButton();
        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblAnstallDatum = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();
        tfAnstallDatum = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEfternamn = new javax.swing.JTextField();
        tfFornamn = new javax.swing.JTextField();
        tfLosenord = new javax.swing.JTextField();
        lblEpostBad = new javax.swing.JLabel();
        cbAvdelning = new javax.swing.JComboBox<>();
        lblLyckades = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnRandom = new javax.swing.JButton();
        lblDatumBad1 = new javax.swing.JLabel();
        lblTelefonBad = new javax.swing.JLabel();
        lblAdressBad = new javax.swing.JLabel();
        lblEfternamnBad = new javax.swing.JLabel();
        lblFornamnBad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSkapa.setText("Skapa");
        btnSkapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaActionPerformed(evt);
            }
        });

        lblFornamn.setText("Förnamn");

        lblEfternamn.setText("Efternamn");

        lblAdress.setText("Adress");

        lblEpost.setText("Epost");

        lblTelefon.setText("Telefon");

        lblAnstallDatum.setText("Anställningsdatum");

        lblLosenord.setText("Lösenord");

        lblAvdelning.setText("Avdelning");

        tfAnstallDatum.setText("yyyy-mm-dd");
        tfAnstallDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnstallDatumActionPerformed(evt);
            }
        });

        tfTelefon.setText("123-123-1234");
        tfTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonActionPerformed(evt);
            }
        });

        tfEpost.setText("example@mail.com");
        tfEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEpostActionPerformed(evt);
            }
        });

        tfAdress.setText("123 blabla, bobla");

        tfEfternamn.setText("Efternamn");

        tfFornamn.setText("Förnamn");

        tfLosenord.setText("Lösenord");
        tfLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLosenordActionPerformed(evt);
            }
        });

        lblEpostBad.setForeground(new java.awt.Color(255, 0, 51));
        lblEpostBad.setText("!");

        cbAvdelning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Klimat", "Samhälle", "Teknik" }));

        lblLyckades.setForeground(new java.awt.Color(51, 204, 0));
        lblLyckades.setText("Lyckades!");

        lblError.setForeground(new java.awt.Color(255, 0, 51));
        lblError.setText("Error!");

        btnRandom.setText("Random");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        lblDatumBad1.setForeground(new java.awt.Color(255, 0, 51));
        lblDatumBad1.setText("!");

        lblTelefonBad.setForeground(new java.awt.Color(255, 0, 51));
        lblTelefonBad.setText("!");

        lblAdressBad.setForeground(new java.awt.Color(255, 0, 51));
        lblAdressBad.setText("!");

        lblEfternamnBad.setForeground(new java.awt.Color(255, 0, 51));
        lblEfternamnBad.setText("!");

        lblFornamnBad.setForeground(new java.awt.Color(255, 0, 51));
        lblFornamnBad.setText("!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnstallDatum)
                            .addComponent(lblTelefon)
                            .addComponent(lblEpost)
                            .addComponent(lblAdress)
                            .addComponent(lblEfternamn)
                            .addComponent(lblFornamn)
                            .addComponent(lblLosenord)
                            .addComponent(lblAvdelning))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfAnstallDatum)
                                    .addComponent(tfLosenord)
                                    .addComponent(tfTelefon)
                                    .addComponent(tfEpost)
                                    .addComponent(tfAdress)
                                    .addComponent(tfEfternamn)
                                    .addComponent(tfFornamn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEpostBad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(btnRandom))
                                    .addComponent(lblDatumBad1)
                                    .addComponent(lblTelefonBad)
                                    .addComponent(lblAdressBad)
                                    .addComponent(lblEfternamnBad)
                                    .addComponent(lblFornamnBad)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSkapa)
                        .addGap(32, 32, 32)
                        .addComponent(lblLyckades)
                        .addGap(72, 72, 72)
                        .addComponent(lblError)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFornamn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFornamnBad)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEfternamn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEfternamnBad)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdress)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAdressBad)))
                                .addGap(12, 12, 12)
                                .addComponent(lblEpost))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEpostBad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTelefon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAnstallDatum))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefonBad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfAnstallDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDatumBad1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLosenord, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRandom)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAvdelning))
                    .addComponent(cbAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSkapa)
                    .addComponent(lblLyckades)
                    .addComponent(lblError))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonActionPerformed

    
    private void tfEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEpostActionPerformed
    
    }//GEN-LAST:event_tfEpostActionPerformed
    // TODO add your handling code here:

    private void tfLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLosenordActionPerformed

    private void btnSkapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaActionPerformed
            totalKontroll(idb);
        if(kontrollOk==true){
            try{
            String sqlFraga="INSERT INTO anstalld VALUES(" + hogstaAid(idb) + ", '" + tfFornamn.getText() +"', '" 
                    + tfEfternamn.getText() + "', '" + tfAdress.getText() + "', '"+tfEpost.getText() + "', '" + tfTelefon.getText() + "', '" 
                    + tfAnstallDatum.getText() + "', '" + tfLosenord.getText() + "', " + getAvdelning() + ")";
            System.out.println(sqlFraga);
            idb.insert(sqlFraga);
            
         
            }
            catch(Exception ex){
                System.out.println(ex.getMessage());
                }
            lblLyckades.setVisible(true);
            lblError.setVisible(false);
            }
        
        else if (kontrollOk==false){
            lblError.setVisible(true);
            
        }
    }//GEN-LAST:event_btnSkapaActionPerformed

    private void totalKontroll(InfDB idb){
        Boolean totOk=true;
        if(kontroll(idb)==false){
            totOk=false;
        }
        else if(!datumKontroll(idb)){
            totOk=false;
        }
        else if(!fornamnKontroll(idb)) {
        totOk = false;
        }
        else if(!efternamnKontroll(idb)) {
        totOk = false;
        }
        else if(!adressKontroll(idb)) {
        totOk = false;
        }
        else if(!telefonKontroll(idb)) {
        totOk = false;
        }
        
        kontrollOk=totOk;
    }
    
    
    
    
    
    
    public boolean datumKontroll(InfDB idb){
        Validering valid = new Validering(idb); 
    
    // Hämta text från textfältet
    String datum = tfAnstallDatum.getText(); 
    
    // Kontrollera om e-postadressen är giltig
    if (valid.checkDatum(datum)) {
        lblDatumBad1.setVisible(false); // Göm varning
        return true;
    } else {
        lblDatumBad1.setVisible(true); // Visa varning
        return false;
    }
    }
    
    public boolean fornamnKontroll(InfDB idb) {
        Validering valid = new Validering(idb);
        String fornamn = tfFornamn.getText();
    if (valid.checkFornamn(fornamn)) {
        lblFornamnBad.setVisible(false); // Göm varning
        return true;
    } else {
        lblFornamnBad.setVisible(true); // Visa varning
        return false;
    }
    }
    
    public boolean efternamnKontroll(InfDB idb) {
        Validering valid = new Validering(idb);
        String efternamn = tfEfternamn.getText();
    if (valid.checkEfternamn(efternamn)) {
            lblEfternamnBad.setVisible(false);
            return true;
    } else {
            lblEfternamnBad.setVisible(true);
            return false;
        }
    }
    
    public boolean adressKontroll(InfDB idb) {
        Validering valid = new Validering(idb);
        String adress = tfAdress.getText();
        if (valid.checkAdress(adress)) {
            lblAdressBad.setVisible(false);
            return true;
        } else {
            lblAdressBad.setVisible(true);
            return false;
        }}
    
        
     public boolean telefonKontroll(InfDB idb) {
        Validering valid = new Validering(idb);
        String telefon = tfTelefon.getText();
    if (valid.checkTelefon(telefon)) {
            lblTelefonBad.setVisible(false);
            return true;
    } else {
            lblTelefonBad.setVisible(true);
            return false;
    }
    }
    
    public boolean kontroll(InfDB idb){
    Validering valid = new Validering(idb); 
    
    // Hämta text från textfältet
    String epost = tfEpost.getText(); 
    
    // Kontrollera om e-postadressen är giltig
    if (valid.checkEpost(epost)) {
        lblEpostBad.setVisible(false); // Göm varning
        return true;
    } else {
        lblEpostBad.setVisible(true); // Visa varning
        return false;
        
    }}
                                           
    public int hogstaAid(InfDB idb){
        int hogsta=0;
        String sqlFraga="Select MAX(aid) FROM anstalld";
        try{
            String max=idb.fetchSingle(sqlFraga);
            hogsta=Integer.parseInt(max);
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        System.out.println(hogsta);
        return hogsta+1;
    }
private int getAvdelning(){
    int avdelning=0;
    String val=cbAvdelning.getSelectedItem().toString();
    switch (val) {
        case "Klimat":
            avdelning=1;
            break;
        case "Teknik":
            avdelning=3;
            break;
        case "Samhälle":
            avdelning=2;
            break;
        default:
            break;
    }
   return avdelning;
}


    public String randomPassword(){
        String losen="";
        for(int i=0; i<11; i++){
            int ny=randomizer.nextInt(9);
            String nya=Integer.toString(ny);
            losen+=nya;
        }
        return losen;
    }
    
    
    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
       tfLosenord.setText(randomPassword());
    }//GEN-LAST:event_btnRandomActionPerformed

    private void tfAnstallDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnstallDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnstallDatumActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LaggTillAnstalld().setVisible(true);
            }
});
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnSkapa;
    private javax.swing.JComboBox<String> cbAvdelning;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAdressBad;
    private javax.swing.JLabel lblAnstallDatum;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblDatumBad1;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEfternamnBad;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblEpostBad;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblFornamnBad;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblLyckades;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTelefonBad;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAnstallDatum;
    private javax.swing.JTextField tfEfternamn;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfFornamn;
    private javax.swing.JTextField tfLosenord;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
