/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author linneagottling
 */
public class MinAvdelning extends javax.swing.JFrame {

    private InfDB idb;
    private int avdNmr;

    /**
     * Initierar MinAvdelning objekt 
     * 
     * Klass visar fönster som leder vidare till användarens avdelnings projekt och anställda
     *
     * @param idb initierar fält för att interagera med databasen
     * @param ePost inloggad användar epost
     */
    public MinAvdelning(InfDB idb, String ePost) {
        this.idb = idb;
        initComponents();
        lblAvdNamn.setText(avdNamn(ePost));
        setAvdNummer(ePost);
    }

    /**
     * hämtar inloggan användares avdelningsnamn
     *
     * @param ePost användarens epost används för att söka i databasen efter
     * rätt användares avdelning
     */
    private String avdNamn(String ePost) {
        String avdelning = " ";
        try {
            String sqlFraga = "SELECT namn FROM avdelning WHERE avdid = "
                    + "(SELECT avdelning FROM anstalld WHERE ePost= '" + ePost + "')";
            avdelning = idb.fetchSingle(sqlFraga);
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }

        return avdelning;
    }

    /**
     * hämtar inloggan användares avdelnings nummer
     *
     * @param ePost användarens epost används för att söka i databasen efter
     * rätt användares avdelning
     */
    private void setAvdNummer(String ePost) {
        int nmr = 0;
        try {
            String sqlFraga = "SELECT avdid FROM avdelning WHERE avdid = "
                    + "(SELECT avdelning FROM anstalld WHERE ePost= '" + ePost + "')";
            String svar = idb.fetchSingle(sqlFraga);
            nmr = Integer.parseInt(svar);
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }

        avdNmr = nmr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvdelning = new javax.swing.JLabel();
        lblAvdNamn = new javax.swing.JLabel();
        btSeAnstallda = new javax.swing.JButton();
        btSeProjekt = new javax.swing.JButton();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAvdelning.setText("Min avdelning");

        lblAvdNamn.setText("Avd");

        btSeAnstallda.setText("Se anställda");
        btSeAnstallda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeAnstalldaActionPerformed(evt);
            }
        });

        btSeProjekt.setText("Se projekt");
        btSeProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeProjektActionPerformed(evt);
            }
        });

        btBack.setText("X");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSeProjekt)
                            .addComponent(btSeAnstallda)
                            .addComponent(lblAvdNamn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvdelning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(btBack)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(btBack))
                .addGap(9, 9, 9)
                .addComponent(btSeProjekt)
                .addGap(12, 12, 12)
                .addComponent(btSeAnstallda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(lblAvdNamn)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSeAnstalldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeAnstalldaActionPerformed
        new AvdAnstallda(idb, avdNmr).setVisible(true);
    }//GEN-LAST:event_btSeAnstalldaActionPerformed

    private void btSeProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeProjektActionPerformed
        new AvdProjekt(idb, avdNmr).setVisible(true);
    }//GEN-LAST:event_btSeProjektActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MinAvdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btSeAnstallda;
    private javax.swing.JButton btSeProjekt;
    private javax.swing.JLabel lblAvdNamn;
    private javax.swing.JLabel lblAvdelning;
    // End of variables declaration//GEN-END:variables
}
