/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author frida.selin
 */
public class OmPartner extends javax.swing.JFrame {

    private InfDB idb;
    private String projektId;
    private String partnerID;
    private String aid;

    /**
     * Skapar nytt OmPartner objekt
     * @param idb
     * @param partnerPid
     * @param aid
     * @param projektId
     */
    public OmPartner(InfDB idb, String partnerPid, String aid, String projektId) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.partnerID = partnerPid;
        this.aid = aid;
        this.projektId = projektId;
        this.idb = idb;

        setInfo();
    }

    private void setInfo() {

        lblH1PartnerNamn.setText(getString(partnerID, partnerNamn()));
        lblAdress.setText(getString(partnerID, adress()));
        lblBranch.setText(getString(partnerID, branch()));
        lblStad.setText(getStad(partnerID));
        txtAreaKontaktPers.setText(getKontaktInfo());
    }
    
    
    private String getString(String partnerPid, String info) {
        String valdString = " ";
        try {
            String sqlFraga = "SELECT " + info + " FROM partner where pid = '" + partnerPid + "'";
            valdString = idb.fetchSingle(sqlFraga);
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }

        return valdString;
    }

    private String partnerNamn() {
        String partnerNamn = "namn";
        return partnerNamn;
    }

    private String adress() {
        String partnerNamn = "adress";
        return partnerNamn;
    }

    private String branch() {
        String partnerNamn = "branch";
        return partnerNamn;
    }

    private String getStad(String partnerPid) {
        String stad = " ";
        try {
            String sqlFraga = "SELECT stad.namn FROM stad "
                    + "JOIN partner on stad.sid = partner.stad "
                    + "WHERE partner.pid = '" + partnerPid + "'";
            stad = idb.fetchSingle(sqlFraga);
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
        return stad;
    }    
    
    private String getKontaktInfo() {
        String valdString = " ";
        try {
            valdString = (idb.fetchSingle("SELECT kontaktperson FROM partner where pid = '" + partnerID + "'") + "\n" + idb.fetchSingle("SELECT kontaktepost FROM partner where pid = '" + partnerID + "'")  + "\n" + idb.fetchSingle("SELECT telefon FROM partner where pid = '" + partnerID + "'"));
            
            
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
       return valdString; 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblH1PartnerNamn = new javax.swing.JLabel();
        lblH2Branch = new javax.swing.JLabel();
        lblH2Adress = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblH2Kontaktperson = new javax.swing.JLabel();
        lblH2Stad = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaKontaktPers = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        lblH1PartnerNamn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblH1PartnerNamn.setForeground(new java.awt.Color(102, 0, 102));

        lblH2Branch.setText("Branch:");

        lblH2Adress.setText("Adress:");

        lblH2Kontaktperson.setText("Kontaktperson:");

        lblH2Stad.setText("Stad:");

        btnTillbaka.setText("<- Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        txtAreaKontaktPers.setEditable(false);
        txtAreaKontaktPers.setColumns(20);
        txtAreaKontaktPers.setRows(5);
        txtAreaKontaktPers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtAreaKontaktPers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblStad, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblH2Kontaktperson, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTillbaka)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblH1PartnerNamn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblH2Branch, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(lblH2Adress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblBranch, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                    .addComponent(lblAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblH2Stad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnTillbaka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblH1PartnerNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblH2Adress)
                    .addComponent(lblAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblH2Branch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBranch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblH2Stad)
                    .addComponent(lblStad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblH2Kontaktperson)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new OmProjekt(idb, aid, projektId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OmPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OmPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OmPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OmPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new OmProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblH1PartnerNamn;
    private javax.swing.JLabel lblH2Adress;
    private javax.swing.JLabel lblH2Branch;
    private javax.swing.JLabel lblH2Kontaktperson;
    private javax.swing.JLabel lblH2Stad;
    private javax.swing.JLabel lblStad;
    private javax.swing.JTextArea txtAreaKontaktPers;
    // End of variables declaration//GEN-END:variables
}
