/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import TabellDesign.MultiLineCellRenderer;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author linneagottling
 */
public class Statistik extends javax.swing.JFrame {
    
    private InfDB idb;
    private String epost;
    private DefaultTableModel model;

    /**
     * Creates new form Statistik
     */
    public Statistik(InfDB idb, String epost) {
        this.idb=idb;
        this.epost=epost;
        initComponents();
        konstrueraTabell();
        fyllTabell();
        tabellDesign();
    }
    
    private void konstrueraTabell(){
        model = (DefaultTableModel) tbStatistik.getModel();
        model.setRowCount(0);
    }
    
        private void tabellDesign() {
        tbStatistik.getColumnModel().getColumn(0).setPreferredWidth(200);
        tbStatistik.getColumnModel().getColumn(1).setPreferredWidth(316);


        tbStatistik.getColumnModel().getColumn(0).setCellRenderer(new MultiLineCellRenderer());
        tbStatistik.getColumnModel().getColumn(1).setCellRenderer(new MultiLineCellRenderer());


        for (int row = 0; row < tbStatistik.getRowCount(); row++) {
            int rowHeight = tbStatistik.getRowHeight();
            for (int column = 0; column < tbStatistik.getColumnCount(); column++) {
                Component comp = tbStatistik.prepareRenderer(tbStatistik.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }
            tbStatistik.setRowHeight(row, rowHeight);
        }
}
    
    private String getChefId(String epost){
        String aid = " ";
        try {
            
        String sqlFraga = "SELECT aid FROM anstalld WHERE epost = '" + epost + "'";
        aid = idb.fetchSingle(sqlFraga);
        
        } catch (InfException ex) {
            
            System.out.println(ex.getMessage());
        }
        return aid;
    }
    
    private void fyllTabell() {

        try {
            String sqlFraga = "SELECT kostnad, projektnamn FROM projekt "
                    + "WHERE projektchef = " + getChefId(epost);

            ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sqlFraga);

            for (HashMap<String, String> rad : resultat) {
                
                    String projekt = rad.get("projektnamn");
                    String kostnad = rad.get("kostnad");
                   
                    model.addRow(new Object[]{projekt, kostnad});

            }
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }
   
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btClose = new javax.swing.JButton();
        spPanel = new javax.swing.JScrollPane();
        tbStatistik = new javax.swing.JTable();
        lblRubrik = new javax.swing.JLabel();
        lblProjektchef = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();
        lblMedel = new javax.swing.JLabel();
        tfTot = new javax.swing.JTextField();
        tfMedel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btClose.setText("X");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        tbStatistik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Projekt", "Kostnad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spPanel.setViewportView(tbStatistik);

        lblRubrik.setText("Kostnaden för projekt:");

        lblProjektchef.setText("Projektchef");

        lblTot.setText("Totala kostnad:");

        lblMedel.setText("Medel:");

        tfTot.setEditable(false);

        tfMedel.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRubrik)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblMedel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfMedel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTot)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfTot, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btClose))
                    .addComponent(lblProjektchef, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblProjektchef)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btClose)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRubrik)
                        .addGap(18, 18, 18)
                        .addComponent(spPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTot)
                    .addComponent(tfTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedel)
                    .addComponent(tfMedel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Statistik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JLabel lblMedel;
    private javax.swing.JLabel lblProjektchef;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblTot;
    private javax.swing.JScrollPane spPanel;
    private javax.swing.JTable tbStatistik;
    private javax.swing.JTextField tfMedel;
    private javax.swing.JTextField tfTot;
    // End of variables declaration//GEN-END:variables
}
